- name: Httpd installation
  block:
    - name: Install the httpd packages
      yum: name='httpd' state={{ httpd_package_state }} update_cache=yes cache_valid_time=1800


- name: Httpd configuration
  block:
    - name: Install the httpd configuration
      template: src=httpd.conf.j2 dest=/etc/redis.conf owner=root group=root mode=0755
      notify: Restart httpd
