---

- name: Logstash installation
  block:
    - name: Install the logstash packages
      yum: name={{ logstash_packages }} state={{ logstash_package_state }} update_cache=yes

- name: Logstash configuration
  block:
    - name: Install the logstash JVM options
      template: src=logstash-jvm.options.j2 dest=/etc/logstash/jvm.options owner=root group=logstash mode=0644
      notify: Restart logstash

    - name: Install the logstash configuration
      template: src=logstash.yml.j2 dest=/etc/logstash/logstash.yml owner=root group=logstash mode=0644
      notify: Restart logstash

    - name: Configure Logstash shipper pipeline
      template: src=files/logstash/logstash-shipper.conf dest=/etc/logstash/logstash-shipper.conf owner=root group=logstash mode=0644
      notify: Restart logstash
    
    - name: Configure Logstash indexer pipeline
      template: src=files/logstash/logstash-indexer.conf dest=/etc/logstash/logstash-indexer.conf owner=root group=logstash mode=0644
      notify: Restart logstash

    - name: Configure Logstash pipelines
      template: src=files/logstash/pipelines.yml dest=/etc/logstash/pipelines.yml owner=root group=logstash mode=0644
      notify: Restart logstash

    - name: Configure Logstash pipelines filters
      template: src='files/logstash/conf.d/{{ item.src }}' dest='/etc/logstash/conf.d/{{ item.path }}' owner=root group=logstash mode=0644
        with_filetree: '{{ templates_source }}'
      notify: Restart logstash
