---

- import_tasks: prerequisites.yml
  when: inventory_hostname in groups["elasticsearch"]

- import_tasks: repository.yml
  when: inventory_hostname in groups["elasticsearch","filebeat"]

- import_tasks: elasticsearch.yml
  when: inventory_hostname in groups["elasticsearch"]

- import_tasks: redis.yml
  when: inventory_hostname in groups["logstash"]

- import_tasks: logstash.yml
  when: inventory_hostname in groups["logstash"]

- import_tasks: apache.yml
  when: inventory_hostname in groups["kibana"]
  
- import_tasks: kibana.yml
  when: inventory_hostname in groups["kibana"]

- import_tasks: filebeat.yml
  when: inventory_hostname in groups["filebeat"]

- import_tasks: services.yml
