---

- hosts: all
  tasks:
    - name: Install dependencies
        file: dependencies.yml
    - name: Install Elastic7 Repository
        file: elastic_repo.yml

- hosts: elasticsearch
  tasks:
    - name: Install elasticsearch
      file: elasticsearch.yml

- hosts: logstash
  tasks:
    - name: Install logstash
      file: logstash.yml
    - name: Install redis
      file: redis.yml

- hosts: kibana
  tasks: 
    - name: Install kibana
      file: kibana.yml
    - name: Install httpd
      file: httpd.yml

- hosts: all
  tasks:
    - name: Start services
      file: services.yml
