---

- name: Redis installation
  block:
    - name: Install the redis packages
      yum: name='redis' state='present' update_cache=yes
      notify: Restart redis


- name: Elasticsearch configuration
  block:
    - name: Install the redis configuration
      template: src=redis.conf.j2 dest=/etc/redis.conf owner=redis group=root mode=0640
      notify: Restart redis
