---
- name: Restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  when: inventory_hostname in groups["elasticsearch"]

- name: Restart logstash
  service: name=logstash state=restarted enabled=yes
  when: inventory_hostname in groups["logstash"]

- name: Restart redis
  service: name=redis state=restarted enabled=yes
  when: inventory_hostname in groups["logstash"]

- name: Restart kibana
  service: name=kibana state=restarted enabled=yes
  when: inventory_hostname in groups["kibana"]

- name: Restart apache
  service: name=httpd state=restarted enabled=yes
  when: inventory_hostname in groups["kibana"]

- name: Restart filebeat
  service: name=filebeat state=restarted enabled=yes
  when: inventory_hostname in groups["filebeat"]

- name: Restart apache
  service: name=httpd state=restarted enabled=yes
  when: inventory_hostname in groups["filebeat"]
