---
- name: Restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  when: elasticsearch_enabled | bool
  ignore_errors: True

- name: Restart logstash
  service: name=logstash state=restarted enabled=yes
  when: logstash_enabled | bool

- name: Restart kibana
  service: name=kibana state=restarted enabled=yes
  when: kibana_enabled | bool

- name: Restart redis
  service: name=redis state=restarted enabled=yes
  when: redis_enabled | bool

- name: Restart httpd
  service: name=httpd state=restarted enabled=yes
  when: httpd_enabled | bool
